const fs = require('node:fs');
const path = require('node:path');
const { resolveDataDir } = require('./dataDir.cjs');
const { readLuaVariable } = require('./luaTableReader.cjs');
const { getProxyConfig } = require('./proxyConfig.cjs');

/**
 * Which addon this build works with. A normal install uses the real GuildToolsLoot addon. A
 * "Guild Tools (Test)" build uses the TEST addon (GuildToolsLootTest, /gtloottest -- generated by
 * scripts/make-test-addon.mjs) instead: it reads that addon's saved data, installs that addon and
 * compares against that addon's version, so a test app and a test addon line up and the real
 * addon is never read or overwritten by test builds.
 */
// The Loot Logger Monitor (test builds only) can look at the REAL addon's data too, read-only, to watch the live
// pipeline from a test build. This flips which addon every read in this file means for the duration of one synchronous
// call, and nothing else: it never writes, and it is always reset.
let flavorOverride = null;

/** Runs `fn` (which must be synchronous) with addonIdentity() answering for 'real' (GuildToolsLoot) or 'test' (GuildToolsLootTest). */
function withAddonFlavor(flavor, fn) {
  const previous = flavorOverride;
  flavorOverride = flavor;
  try {
    return fn();
  } finally {
    flavorOverride = previous;
  }
}

function addonIdentity() {
  const useTestAddon = flavorOverride ? flavorOverride === 'test' : getProxyConfig().testMode;
  if (useTestAddon) {
    const name = 'GuildToolsLootTest';
    // Packaged test build: shipped as an extra resource next to the app; in dev: the generated folder in the repo.
    const candidates = [process.resourcesPath && path.join(process.resourcesPath, 'addon-test', name), path.join(__dirname, '..', '..', 'addon-test', name)].filter(Boolean);
    const srcDir = candidates.find((c) => fs.existsSync(c)) ?? candidates[candidates.length - 1];
    return { name, dbVar: 'GuildToolsLootTestDB', srcDir };
  }
  return { name: 'GuildToolsLoot', dbVar: 'GuildToolsLootDB', srcDir: path.join(__dirname, '..', '..', 'addon', 'GuildToolsLoot') };
}

// Loot history is purely local: it comes from the GuildToolsLoot addon's
// SavedVariables file on THIS machine's WoW installation, not from any server or the
// API proxy -- there's nothing to sync, this only ever reflects whoever's PC Guild
// Tools happens to be running on (see the plan notes for why that's an acceptable v1
// scope: Group Loot broadcasts roll results to the whole raid, so it doesn't matter
// whose client captured them).

const DEFAULT_WOW_PATH = 'C:\\Program Files (x86)\\World of Warcraft\\_retail_';

function configPath() {
  return path.join(resolveDataDir(), 'wow-path.json');
}

function loadConfig() {
  try {
    return JSON.parse(fs.readFileSync(configPath(), 'utf8'));
  } catch {
    return {};
  }
}

// Merges into whatever's already on disk rather than overwriting -- wowPath and
// characterName are set independently (different UI moments), and each needs to leave
// the other alone.
function saveConfig(patch) {
  const merged = { ...loadConfig(), ...patch };
  fs.writeFileSync(configPath(), JSON.stringify(merged, null, 2));
  return merged;
}

function loadConfiguredPath() {
  return loadConfig().wowPath ?? null;
}

function saveConfiguredPath(wowPath) {
  saveConfig({ wowPath });
}

// This PC's raiding character -- needed to resolve chat-tail's "You" quirk (see
// lootChatTail.cjs): WoW's chat log calls the local player's own wins "You". It used
// to be typed in by hand; now it's pulled from the client, best source first:
//   1. a manual override (only set if detection gets it wrong),
//   2. what the addon recorded at login (GuildToolsLootDB.character), and
//   3. the most recently written character folder under WTF/Account/<acct>/<realm>/.
// 2 and 3 both come from the client flushing to disk (on /reload or logout), so
// neither can know a character the officer JUST logged into before that flush --
// the UI says so, and a self-win captured in that window is reconciled against the
// addon's own record later (see lootRecordsStore.cjs's `selfWin`).
function getCharacterOverride() {
  return loadConfig().characterName ?? null;
}

function setCharacterName(name) {
  saveConfig({ characterName: name || null });
}

function readAddonDb() {
  const wowPath = resolveWowPath();
  if (!isRealWowPath(wowPath)) return null;
  const svFile = findSavedVariablesFile(wowPath);
  if (!svFile) return null;
  try {
    return readLuaVariable(fs.readFileSync(svFile, 'utf8'), addonIdentity().dbVar);
  } catch {
    return null;
  }
}

function detectCharacterFromAddon() {
  const c = readAddonDb()?.character;
  if (!c || typeof c.name !== 'string' || !c.name) return null;
  return { name: c.name, at: Number(c.at) > 0 ? Number(c.at) * 1000 : 0 };
}

// The client writes every per-character cache file for a character together when that
// character logs out or reloads, so the newest of them stamps "last character flushed".
const CHARACTER_STAMP_FILES = ['chat-cache.txt', 'layout-local.txt', 'config-cache.wtf'];

function dirsIn(dir) {
  try {
    return fs.readdirSync(dir, { withFileTypes: true }).filter((e) => e.isDirectory()).map((e) => e.name);
  } catch {
    return [];
  }
}

/** Newest character folder under WTF/Account/<account>/<realm>/<character>/ by file mtime, across every account on this PC. @returns {{ name: string, realm: string, at: number } | null} */
function detectCharacterFromWtf(wowPath) {
  const accountsDir = path.join(wowPath, 'WTF', 'Account');
  let best = null;
  for (const account of dirsIn(accountsDir)) {
    for (const realm of dirsIn(path.join(accountsDir, account))) {
      if (realm === 'SavedVariables') continue;
      for (const character of dirsIn(path.join(accountsDir, account, realm))) {
        for (const file of CHARACTER_STAMP_FILES) {
          let at;
          try {
            at = fs.statSync(path.join(accountsDir, account, realm, character, file)).mtimeMs;
          } catch {
            continue;
          }
          if (!best || at > best.at) best = { name: character, realm, at };
        }
      }
    }
  }
  return best;
}

/** @returns {{ name: string | null, source: 'manual' | 'addon' | 'wtf' | null }} */
function resolveCharacter() {
  const override = getCharacterOverride();
  if (override) return { name: override, source: 'manual' };

  const fromAddon = detectCharacterFromAddon();
  const wowPath = resolveWowPath();
  const fromWtf = isRealWowPath(wowPath) ? detectCharacterFromWtf(wowPath) : null;
  // Both are last-flush stamps, so they normally agree. When they don't (an older addon
  // build that never recorded a character, or a character played with the addon off),
  // the newer flush is the more recent character.
  if (fromAddon && fromWtf) return fromWtf.at > fromAddon.at + 60_000 ? { name: fromWtf.name, source: 'wtf' } : { name: fromAddon.name, source: 'addon' };
  if (fromAddon) return { name: fromAddon.name, source: 'addon' };
  if (fromWtf) return { name: fromWtf.name, source: 'wtf' };
  return { name: null, source: null };
}

function getCharacterName() {
  return resolveCharacter().name;
}

function isRealWowPath(candidate) {
  return !!candidate && fs.existsSync(path.join(candidate, 'WTF'));
}

/** Configured path if it still looks real, else the standard Windows default if that looks real, else whatever's configured (may be null). */
function resolveWowPath() {
  const configured = loadConfiguredPath();
  if (isRealWowPath(configured)) return configured;
  if (isRealWowPath(DEFAULT_WOW_PATH)) return DEFAULT_WOW_PATH;
  return configured;
}

/** Account folder names vary per installation, so this scans WTF/Account/* for whichever one actually has our SavedVariables file, rather than asking the officer to type their account name. */
function findSavedVariablesFile(wowPath) {
  const accountsDir = path.join(wowPath, 'WTF', 'Account');
  let entries;
  try {
    entries = fs.readdirSync(accountsDir, { withFileTypes: true });
  } catch {
    return null;
  }
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(accountsDir, entry.name, 'SavedVariables', `${addonIdentity().name}.lua`);
    if (fs.existsSync(candidate)) return candidate;
  }
  return null;
}

/**
 * @returns {{ records: object[], trades: object[], needLosses: object[], status: 'ok' | 'not_configured' | 'addon_not_installed' }}
 */
function getLootRecords() {
  const wowPath = resolveWowPath();
  if (!isRealWowPath(wowPath)) return { records: [], trades: [], needLosses: [], status: 'not_configured' };

  const svFile = findSavedVariablesFile(wowPath);
  if (!svFile) return { records: [], trades: [], needLosses: [], status: 'addon_not_installed' };

  const source = fs.readFileSync(svFile, 'utf8');
  const db = readLuaVariable(source, addonIdentity().dbVar);
  if (!db) return { records: [], trades: [], needLosses: [], status: 'addon_not_installed' };

  return { records: db.records ?? [], trades: db.trades ?? [], needLosses: db.needLosses ?? [], status: 'ok' };
}

function getWowPathConfig() {
  const character = resolveCharacter();
  return {
    configured: loadConfiguredPath(),
    resolved: resolveWowPath(),
    valid: isRealWowPath(resolveWowPath()),
    characterName: character.name,
    characterSource: character.source,
    characterOverride: getCharacterOverride(),
  };
}

function setWowPath(wowPath) {
  saveConfiguredPath(wowPath);
}

// Copies the addon's source (shipped inside this app, see package.json's build.files)
// into <wowPath>/Interface/AddOns/GuildToolsLoot -- read/write via fs directly (not
// fs.copyFile) so this works transparently whether the source lives on a real disk
// (dev mode) or inside the packaged app's read-only asar archive.
function installAddon() {
  const wowPath = resolveWowPath();
  if (!isRealWowPath(wowPath)) throw new Error('WoW installation not found -- set the path first.');

  const { name, srcDir } = addonIdentity();
  const destDir = path.join(wowPath, 'Interface', 'AddOns', name);
  fs.mkdirSync(destDir, { recursive: true });

  for (const file of fs.readdirSync(srcDir)) {
    const content = fs.readFileSync(path.join(srcDir, file));
    fs.writeFileSync(path.join(destDir, file), content);
  }
  return destDir;
}

function readTocVersion(file) {
  try {
    return fs.readFileSync(file, 'utf8').match(/^##\s*Version:\s*(.+?)\s*$/m)?.[1] ?? null;
  } catch {
    return null;
  }
}

/** Numeric, segment-by-segment ("1.10" > "1.9"); missing segments count as 0. */
function compareVersions(a, b) {
  const pa = String(a).split('.').map((n) => parseInt(n, 10) || 0);
  const pb = String(b).split('.').map((n) => parseInt(n, 10) || 0);
  for (let i = 0; i < Math.max(pa.length, pb.length); i++) {
    const d = (pa[i] ?? 0) - (pb[i] ?? 0);
    if (d !== 0) return d < 0 ? -1 : 1;
  }
  return 0;
}

/**
 * The addon copy this build of the app carries vs the one actually installed in WoW --
 * lets Loot History say "your addon is out of date" instead of an officer finding out
 * from a missing feature. Compares the on-disk TOC only: what's running IN the game is
 * whatever it loaded last, so an update still needs a /reload to take effect.
 * @returns {{ bundled: string | null, installed: string | null, status: 'current' | 'outdated' | 'not_installed' | 'no_wow' }}
 */
function getAddonVersionInfo(bundledTocOverride) {
  const identity = addonIdentity();
  const bundled = readTocVersion(bundledTocOverride ?? path.join(identity.srcDir, `${identity.name}.toc`));
  const wowPath = resolveWowPath();
  if (!isRealWowPath(wowPath)) return { bundled, installed: null, status: 'no_wow' };
  const installed = readTocVersion(path.join(wowPath, 'Interface', 'AddOns', identity.name, `${identity.name}.toc`));
  if (!installed) return { bundled, installed: null, status: 'not_installed' };
  if (bundled && compareVersions(installed, bundled) < 0) return { bundled, installed, status: 'outdated' };
  return { bundled, installed, status: 'current' };
}

module.exports = {
  withAddonFlavor,
  getLootRecords,
  getWowPathConfig,
  setWowPath,
  installAddon,
  resolveWowPath,
  isRealWowPath,
  getCharacterName,
  getCharacterOverride,
  setCharacterName,
  resolveCharacter,
  detectCharacterFromWtf,
  getAddonVersionInfo,
  compareVersions,
};
